default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: phase3_project_development

test:
  <<: *default
  database: phase3_project_test


production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: phase3_project_production